"""Generate docs/CONTROLS.md from controls/checks.yaml and SCF rows.json.

The SCF statements come from Beacon's pinned SCF 2026.3 objective rows.
The generator fails closed when rows.json does not match the pinned hash or
when a catalog ao_id is not in rows.json.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

from ..manifest import REPO_ROOT, sha256_hex
from .catalog import Catalog, CatalogError, load_catalog, scf_control_ref

DEFAULT_ROWS = REPO_ROOT.parent / "kfcain" / "beacon" / "beacon" / "scf" / "objectives" / "rows.json"
DOC_PATH = REPO_ROOT / "docs" / "CONTROLS.md"
QUOTE_LIMIT = 200


def rows_path() -> Path:
    return Path(os.environ.get("MEMBRANE_SCF_ROWS", DEFAULT_ROWS))


def load_rows(catalog: Catalog, path: Path | None = None) -> dict[str, dict]:
    path = Path(path or rows_path())
    if not path.is_file():
        raise CatalogError(f"SCF rows.json not found at {path}. Set MEMBRANE_SCF_ROWS.")
    data = path.read_bytes()
    want = catalog.scf_pin.get("rows_json_sha256")
    got = sha256_hex(data)
    if want and got != want:
        raise CatalogError(f"{path}: SHA-256 {got} does not match the pinned {want}")
    doc = json.loads(data)
    if doc.get("catalog_version") != catalog.scf_pin.get("catalog_version"):
        raise CatalogError(f"{path}: catalog_version {doc.get('catalog_version')} is not the pinned version")
    if doc.get("source_sha256") != catalog.scf_pin.get("workbook_sha256"):
        raise CatalogError(f"{path}: workbook hash does not match the pin")
    return {r["ao_id"]: r for r in doc["rows"]}


def verify_scf_ids(catalog: Catalog, rows: dict[str, dict]) -> list[str]:
    return [f"{c.id}: {a}" for c in catalog.checks for a in c.scf_ao if a not in rows]


def _quote(text: str) -> str:
    t = " ".join(text.split())
    return t if len(t) <= QUOTE_LIMIT else t[: QUOTE_LIMIT - 3].rstrip() + "..."


def render(catalog: Catalog, rows: dict[str, dict]) -> str:
    missing = verify_scf_ids(catalog, rows)
    if missing:
        raise CatalogError("SCF ids not in rows.json: " + ", ".join(missing))
    pin = catalog.scf_pin
    L = [
        "# Controls",
        "",
        "<!-- Generated by `membrane checks doc` from controls/checks.yaml. Do not edit by hand. -->",
        "",
        "This file lists each membrane check, its evidence, and its control mapping. "
        "The mapping is membrane's own. NIST and the SCF Council did not review it.",
        "",
        "## Status words",
        "",
        "A check gets one status: PASS, FAIL, NO_EVIDENCE, STALE, or INELIGIBLE. "
        "A control gets one rollup status: MET, PARTIAL, or NOT MET. "
        "MET means every mapped check is PASS. NOT MET means no mapped check is PASS. PARTIAL is the rest. "
        "See docs/CONTRACTS.md section 7.",
        "",
        "## Evidence rules",
        "",
        "- `evidence_kinds` must all have records. Freshness applies to the newest eligible record of each kind.",
        "- `supporting_kinds` join when they exist. An empty supporting kind does not cause NO_EVIDENCE.",
        "- Only `live` records are eligible unless the run passes `--allow-nonlive`. That run is a demonstration.",
        "- A record with `collected_at` after `--now` does not count.",
        "",
        "## SCF source",
        "",
        f"SCF statements below are quotes from the Secure Controls Framework (SCF) {pin.get('catalog_version')}, "
        f"sheet \"{pin.get('source_sheet')}\". Copyright remains with the SCF Council. "
        "License: CC BY-ND 4.0, https://creativecommons.org/licenses/by-nd/4.0/ . "
        f"Workbook SHA-256 `{pin.get('workbook_sha256')}`. "
        f"The quotes come from Beacon's vendored `rows.json` (SHA-256 `{pin.get('rows_json_sha256')}`). "
        f"Quotes longer than {QUOTE_LIMIT} characters are cut and end in \"...\". The ids are unchanged.",
        "",
        "ISO/IEC 42001 Annex A ids are not in this file. The standard text is not public, "
        "and membrane does not cite ids that it cannot check against the source.",
        "",
        "## OSCAL output",
        "",
        "`membrane checks run` writes `assessment-results.oscal.json` (OSCAL 1.1.3). "
        "Each check is one observation. Each control is one finding. "
        "NIST findings target `<control>_smt` as a `statement-id`. SCF findings target the `ao_id` as an `objective-id`. "
        "MET maps to `satisfied`. PARTIAL and NOT MET map to `not-satisfied`. "
        "The prop `membrane-control-status` keeps the membrane word. "
        "`import-ap` points at `./assessment-plan.placeholder.json`. That file does not exist. "
        "Replace the href with the real assessment plan before you use the document in a package.",
        "",
        "## Summary",
        "",
        "| Check | Title | Evidence | Max age (h) | NIST SP 800-53 Rev 5 | SCF ao_id |",
        "| --- | --- | --- | ---: | --- | --- |",
    ]
    for c in catalog.checks:
        ev = ", ".join(c.evidence_kinds) + (f" (+ {', '.join(c.supporting_kinds)})" if c.supporting_kinds else "")
        L.append(f"| {c.id} | {c.title} | {ev} | {c.max_age_hours:g} | {', '.join(c.nist_800_53) or '-'} | "
                 f"{', '.join(c.scf_ao) or '-'} |")
    L.append("")
    L.append("## Checks")
    L.append("")
    for c in catalog.checks:
        L += [
            f"### {c.id} {c.title}",
            "",
            f"- Question: {c.question}",
            f"- Target: {c.target}",
            f"- Evidence kinds: {', '.join(c.evidence_kinds)}",
            f"- Supporting kinds: {', '.join(c.supporting_kinds) or 'none'}",
            f"- Max age: {c.max_age_hours:g} hours",
            f"- Remediation on FAIL: {c.remediation}",
            f"- NIST SP 800-53 Rev 5: {', '.join(c.nist_800_53) or 'none'}",
            "",
        ]
        if c.scf_ao:
            L.append("| SCF ao_id | SCF control | SCF statement (quote) |")
            L.append("| --- | --- | --- |")
            for a in c.scf_ao:
                L.append(f"| {a} | {scf_control_ref(a)} | \"{_quote(rows[a]['statement'])}\" |")
        else:
            L.append("No SCF row fits this check.")
        L.append("")
    return "\n".join(L)


def write_doc(catalog_path: Path | None = None, rows: Path | None = None, out: Path | None = None) -> Path:
    catalog = load_catalog(catalog_path)
    text = render(catalog, load_rows(catalog, rows))
    out = Path(out or DOC_PATH)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    return out
